name: python app workflow
on:
 pull_request:
  types: [closed]
permissions:
 pull-requests: write

jobs:
 Build:
  runs-on: ubuntu-latest

  steps:
   - name: checkout repository
     uses: actions/checkout@v4

   - name: install python
     uses: actions/setup-python@v5
     with:
      python-version: '3.12'

   - name: print python version
     run: python --version

   - name: install python dependencies
     run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt

   - name: Check FastAPI version
     run: |
      python -c "import fastapi; print(f'FastAPI version: {fastapi.__version__}')"
      
  
  
 
 
